# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1833c71230d1494a2f9333ca04f0dfb9d88f9cfb1e1c5601483fd21ad0c6cef59a1ee42651949543cf03e8dbd28abc6d752cce207654fc16c0bbf5c6991ca334

test:
  secret_key_base: 6a70fb61ad3541c2b3a22b37ee622272cde6aa14a6f73b80ffb725040bb8f43f8f2842436e71886611d293a6c68cc17ec89b811b90221c7b9cad560afa06ff68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
